[package]
name = "shapes"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
itertools = "0.14.0"
math = { version = "0.1.0", path = "../math" }
prismatic = { version = "0.1.0", path = "../prismatic" }
num-traits = "0.2.19"
